spring:
  application:
    name: ORIS_2
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/spring1
    username: postgres
    password: Uekz2005
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  port: 8081

info:
  app:
    name: ORIS_2
    description: homework
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
